language: node_js
node_js:
  - "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
  - yarn global add now 
script:
  - yarn lint
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - yarn build  
    - now build --public --token $NOW_TOKEN
    - now alias --token $NOW_TOKEN